Adds a message that allows loading environments via a topic
gazebosim/gz-msgs pull request #320
Opened 2022-12-20 14:12 UTC by arjo129

# 🦟 Bug fix

Fixes #<NUMBER>

## Summary
Required by https://github.com/gazebosim/gz-sim/pull/1842

Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>
## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-12-20 14:16 UTC, ahcorde submitted a review, later dismissed

2022-12-20 14:16 UTC, ahcorde commented on include/gz/msgs/Utility.hh
> +      const math::SphericalCoordinates::CoordinateType &_sc);
```suggestion
    /// \param[in] _coord The spherical coordinates to convert
    /// \return A gz::math::SphericalCoordinatesType object
    GZ_MSGS_VISIBLE
    msgs::SphericalCoordinatesType ConvertCoord(
      const math::SphericalCoordinates::CoordinateType &_coord);
```

2022-12-20 14:16 UTC, ahcorde commented on proto/gz/msgs/data_load_options.proto
> +message DataLoadPathOptions
```suggestion
import "gz/msgs/spherical_coordinates.proto";

/// \brief Used for specifying how to load environmental data
message DataLoadPathOptions
```

2022-12-20 15:18 UTC, caguero commented on include/gz/msgs/Utility.hh
> +    /// \param[in] _coord The spherical coordinates to convert
The spherical coordinate type ...

2022-12-20 15:18 UTC, caguero commented on include/gz/msgs/Utility.hh
> +    /// \brief Convert a msgs::SphericalCoordinatesType to an
The other way, from `math::` to `msgs::` .

2022-12-20 15:18 UTC, caguero commented on proto/gz/msgs/data_load_options.proto
> +    /// \brief
Add doc.

2022-12-20 15:18 UTC, caguero commented on src/Utility.cc
> +          return math::SphericalCoordinates::CoordinateType::LOCAL2;
This block returns a warning on Windows as we don't return anything if none of the previous conditions are met.

2022-12-20 15:18 UTC, caguero commented on src/Utility.cc
> +          return msgs::SphericalCoordinatesType::LOCAL2;
This block returns a warning on Windows as we don't return anything if none of the previous conditions are met.

2023-01-20 21:21 UTC, caguero approved these changes
Tiny comment, otherwise looks good to me.

2023-01-20 21:21 UTC, caguero commented on proto/gz/msgs/data_load_options.proto
> +     /// \brief Is the data static in time
Nit: extra space here.

2023-01-25 03:19 UTC, arjo129 commented
I suggest holding off on merging this till gazebosim/gz-sim#1842 is complete.

2023-02-28 08:55 UTC, ahcorde requested changes

2023-02-28 08:55 UTC, ahcorde commented on proto/gz/msgs/data_load_options.proto
> + * Copyright (C) 2022 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2023 Open Source Robotics Foundation
```

2023-04-26 00:06 UTC, mjcarroll requested changes
There are some open comments from Carlos here, if you could address them.

2023-05-10 07:55 UTC, ahcorde approved these changes

2023-05-17 04:37 UTC, arjo129 commented
@mjcarroll I've addressed the issues. It's waiting on a :heavy_check_mark: from you.

2023-08-04 18:55 UTC, mjcarroll approved these changes

2023-08-04 21:54 UTC, merged