Standalone executable for gz_msgs
gazebosim/gz-msgs pull request #353
Opened 2023-06-22 18:54 UTC by mjcarroll

# 🎉 New feature

## Summary

Adds a C++ standalone executable for the gz-msgs command line interface.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-06-22 21:34 UTC, azeey reviewed
LGTM! One small comment regarding absolute paths.

2023-06-22 21:34 UTC, azeey commented on src/cmd/cmdmsgs.rb.in
> +    if exe_name[0] == '/'
I don't think this works on windows. I recommend using `pathname` as
https://github.com/gazebosim/gz-sim/blob/001dd9b829eb8e8b4465d87c6c70ccf4ee2e6b6a/src/cmd/cmdsim.rb.in#L355

2023-06-23 07:43 UTC, ahcorde requested changes

2023-06-23 07:43 UTC, ahcorde commented on src/cmd/msgs_main.cc
> +  _app.callback([opt](){
```suggestion
     }, "Get info about the specified message type.");

  _app.callback([opt](){
```

2023-06-23 07:43 UTC, ahcorde commented on src/cmd/msgs_main.cc
> +
```suggestion
#include <string>
```

2023-06-23 15:19 UTC, mjcarroll commented
After talking with @j-rivero, it makes more sense to target this to `harmonic`

2023-06-23 15:19 UTC, closed without merging