Support standalone executable in gz-msgs11
gazebosim/gz-msgs pull request #357
Opened 2023-06-27 16:46 UTC by mjcarroll

# 🎉 New feature

Reworks #353 for `ionic`

## Summary

This adds support for a standalone gz-utils::cli based executable for message introspection.

It additionally modifies the ruby scripts so that gz-tools will continue to work.

This also removes the `compiled` component introduced in #339, as it's not really necessary with the new standalone executable structure.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-06-27 17:38 UTC, ahcorde requested changes

2023-06-27 17:38 UTC, ahcorde commented on core/cmd/msgs_main.cc
> +#include <string>
```suggestion
#include <iostream>
#include <memory>
#include <string>
```

2023-06-27 17:38 UTC, ahcorde commented on core/cmd/msgs_main.cc
> +}
```suggestion
    return 0;
}
```

2023-12-12 21:45 UTC, azeey commented
The description says "Reworks https://github.com/gazebosim/gz-msgs/pull/353 for harmonic", but the PR is targeting `main`. Is that right?

2023-12-13 14:41 UTC, mjcarroll commented
> The description says "Reworks https://github.com/gazebosim/gz-msgs/pull/353 for harmonic", but the PR is targeting main. Is that right?

It should be for `main`, so ionic at this point.

2023-12-13 15:29 UTC, ahcorde requested changes

2023-12-13 15:29 UTC, ahcorde commented on core/cmd/msgs_main.cc
> +#include <string>
did you add the header?

2023-12-13 15:44 UTC, mjcarroll commented on core/cmd/msgs_main.cc
> +#include <string>
Whoops, bad merge, thanks.

2024-01-03 20:45 UTC, ahcorde approved these changes

2024-01-03 20:45 UTC, merged