Deprecate LOCAL2 in `SphericalCoordinates`
gazebosim/gz-msgs pull request #450
Opened 2024-08-19 07:53 UTC by arjo129

# 🦟 Bug fix

## Summary
With the introduction of https://github.com/gazebosim/gz-math/pull/616. We will be deprecating `LOCAL2` as a work around in favor or `LOCAL`. As part of this change, its probably a good idea to update `gz-msgs` as well.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-08-20 00:39 UTC, iche033 commented
there is one gcc deprecation warning left: https://build.osrfoundation.org/job/gz_msgs-ci-pr_any-noble-amd64/7/gcc/

2024-08-20 01:07 UTC, arjo129 commented
Yeah, I'm not exactly sure how to solve this as the warning is coming from the generated protobuf. It seems like the Proto compiler reuses the highest value. There are several options. Perhaps I could introduce a `DO_NOT_USE` in the highest proto?

2024-08-20 14:35 UTC, Crola1702 commented
This change in https://github.com/gazebosim/gz-math/pull/616 triggered a regression in gz-transport14-debbuilder:

Reference build:
* [gz-transport14-debbuilder-jammy#512](https://build.osrfoundation.org/job/gz-transport14-debbuilder/512)
* [gz-transport14-debbuilder-noble#513](https://build.osrfoundation.org/job/gz-transport14-debbuilder/513)


Log output:
```
/usr/lib/x86_64-linux-gnu/pkgconfig/../../../include/gz/msgs11/gz/msgs/convert/SphericalCoordinates.hh:80:54: warning: ‘gz::math::v8::SphericalCoordinates::LOCAL2’ is deprecated [-Wdeprecated-declarations]
   80 |   return math::SphericalCoordinates::CoordinateType::LOCAL2;
      |                                                      ^~~~~~
/usr/lib/x86_64-linux-gnu/pkgconfig/../../../include/gz/math8/gz/math/SphericalCoordinates.hh:82:15: note: declared here
   82 |               LOCAL2 GZ_LOCAL2_DEPRECATED = 5
      |               ^~~~~~
autopkgtest [11:18:31]: @@@@@@@@@@@@@@@@@@@@ summary
build                FAIL stderr: In file included from /usr/lib/x86_64-linux-gnu/pkgconfig/../../../include/gz/msgs11/gz/msgs/Utility.hh:27,
autopkgtest [11:18:31]: Binaries: resetting testbed apt configuration
```

@arjo129  can you please take a look?

2024-08-20 14:44 UTC, peci1 commented
@Crola1702 Those errors should be fixed by this PR.

2024-08-22 01:56 UTC, peci1 requested changes
This PR looks good, but there still remain the warnings from protobuf-generated files. I fixed that in #451.

2024-08-22 02:55 UTC, arjo129 commented
Thanks @peci1! Will use that PR.

2024-08-22 02:55 UTC, closed without merging