Remove deprecations: tock
gazebosim/gz-msgs pull request #476
Opened 2024-12-04 20:41 UTC by caguero

# 🦟 Bug fix

Perform the tock of the tick-tock cycle and remove / move deprecated code.

@peci1

## Summary

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-12-05 08:13 UTC, peci1 requested changes
Just one little suggestion, otherwise LGTM.

2024-12-05 08:13 UTC, peci1 commented on Migration.md
> +1. **spherical_coordinates.hh**
```suggestion
1. **SphericalCoordinates.hh**
```

2024-12-19 21:29 UTC, peci1 approved these changes

2024-12-19 22:21 UTC, azeey approved these changes
One small change, otherwise, LGTM!

2024-12-19 22:21 UTC, azeey commented on Migration.md
> +    + This message is deprecated. Use `NavSat` instead.
```suggestion
    + This message is deprecated. Use `NavSatSensor` instead.
```

2024-12-19 22:34 UTC, merged